import { Object3D } from "three";
import { Scene as SceneBase } from "three/index";
import { BindingCallback } from "../src/Binding/Binding";
import { Cursor } from "../src/Events/CursorManager";
import { Events } from "../src/Events/Events";
import { Object3DExtPrototype } from "../src/Patch/Object3D";
import { DistinctTargetArray } from "../src/Utils/DistinctTargetArray";
import { SceneExtPrototype } from "../src/Patch/Scene";
import { EventsDispatcher } from "../src/Events/EventsDispatcher";

export class Scene extends SceneBase  implements Object3DExtPrototype, SceneExtPrototype {
    /** @internal */ __boundObjects: DistinctTargetArray;
    /** @internal */ __needsRender: boolean;
    /** @internal */ __smartRendering: boolean;
    __smartRenderingPatched: boolean;
    /** @internal */ __enabled: boolean;
    /** @internal */ __visible: boolean;
    activeSmartRendering(): this;
    __scene: Scene;
    needsRender(): void;
    __boundCallbacks: BindingCallback[];
    __manualDetection: boolean;
    setManualDetectionMode(): void;
    detectChanges(recursive?: boolean): void;
    bindProperty<T extends keyof this>(property: T, getCallback: () => this[T], renderOnChange?: boolean): this;
    unbindProperty<T extends keyof this>(property: T): this;
    __eventsDispatcher: EventsDispatcher;
    __vec3Patched: boolean;
    __rotationPatched: boolean;
    override parent: Object3D;
    override children: Object3D[];
    draggable: boolean;
    dragging: boolean;
    clicking: boolean;
    activable: boolean;
    get firstActivable(): Object3D;
    active: boolean;
    hovered: boolean;
    enabled: boolean;
    enabledUntilParent: boolean;
    interceptByRaycaster: boolean;
    objectsToRaycast: Object3D[];
    cursor: Cursor;
    cursorOnDrag: Cursor;
    on<K extends keyof Events>(type: K | K[], listener: (args: Events[K]) => void): (args: Events[K]) => void;
    hasEvent<K extends keyof Events>(type: K, listener: (args: Events[K]) => void): boolean;
    off<K extends keyof Events>(type: K, listener: (args: Events[K]) => void): void;
    trigger<K extends keyof Events>(type: K, args: Events[K]): void;
    triggerAncestor<K extends keyof Events>(type: K, args: Events[K]): void;
}
