import { Object3D } from "three";
import { Scene as SceneBase } from "three/index";
import { BindingCallback } from "../src/Binding/Binding";
import { Cursor } from "../src/Events/CursorManager";
import { Events } from "../src/Events/Events";
import { Object3DExtPrototype } from "../src/Patch/Object3D";
import { DistinctTargetArray } from "../src/Utils/DistinctTargetArray";
import { SceneExtPrototype } from "../src/Patch/Scene";
import { EventsDispatcher } from "../src/Events/EventsDispatcher";

export class Scene extends SceneBase implements Object3DExtPrototype, SceneExtPrototype {
    activeSmartRendering(): this;
    enabled: boolean;
    enabledUntilParent: boolean;
    interceptByRaycaster: boolean;
    objectsToRaycast: Object3D[];
    focusable: boolean;
    draggable: boolean;
    hovered: boolean;
    focused: boolean;
    clicking: boolean;
    dragging: boolean;
    cursor: Cursor;
    cursorOnDrag: Cursor;
    get firstFocusable(): Object3D;
    needsRender(): void;
    on<K extends keyof Events>(type: K | K[], listener: (args: Events[K]) => void): (args: Events[K]) => void;
    hasEvent<K extends keyof Events>(type: K, listener: (args: Events[K]) => void): boolean;
    off<K extends keyof Events>(type: K, listener: (args: Events[K]) => void): void;
    trigger<K extends keyof Events>(type: K, args: Events[K]): void;
    triggerAncestor<K extends keyof Events>(type: K, args: Events[K]): void;
    setManualDetectionMode(): void;
    detectChanges(recursive?: boolean): void;
    bindProperty<T extends keyof this>(property: T, getCallback: () => this[T], renderOnChange?: boolean): this;
    unbindProperty<T extends keyof this>(property: T): this;
    /** @internal */ __scene: SceneBase;
    /** @internal */ __boundCallbacks: BindingCallback[];
    /** @internal */ __manualDetection: boolean;
    /** @internal */ __eventsDispatcher: EventsDispatcher;
    /** @internal */ __vec3Patched: boolean;
    /** @internal */ __rotationPatched: boolean;
    /** @internal */ __smartRenderingPatched: boolean;
    /** @internal */ __enabled: boolean;
    /** @internal */ __visible: boolean;
    /** @internal */ __boundObjects: DistinctTargetArray;
    /** @internal */ __needsRender: boolean;
    /** @internal */ __smartRendering: boolean;
}
